"""PPT generation pipeline — integrates HydroClaw-PPT engine."""

from __future__ import annotations

import importlib
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from hydrowriter.config import WriterConfig
from hydrowriter.engine.base_engine import BaseEngine


@dataclass
class PPTResult:
    """Result of PPT generation."""

    output_path: str = ""
    slide_count: int = 0
    success: bool = False
    error: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


class PPTPipeline:
    """Generate PPT slides from structured content.

    Supports two backends:
    1. python-pptx (built-in, lightweight)
    2. HydroClaw-PPT engine (full-featured, via vendor path)
    """

    HYDROCLAW_PPT_PATHS = [
        Path("D:/cowork/HydroClaw_workspace/HydroClaw-PPT"),
        Path("D:/cowork/HydroClaw_workspace/HydroClaw/vendor/HydroClaw-PPT"),
    ]

    def __init__(self, engines: dict[str, BaseEngine] | None = None, config: WriterConfig | None = None):
        self.engines = engines or {}
        self.config = config
        self._pptx = self._load_pptx()

    def _load_pptx(self) -> Any | None:
        try:
            return importlib.import_module("pptx")
        except ImportError:
            return None

    def _find_hydroclaw_ppt(self) -> Path | None:
        for path in self.HYDROCLAW_PPT_PATHS:
            if path.exists() and (path / "generate_final_ppt.py").exists():
                return path
        return None

    async def generate_from_outline(
        self,
        title: str,
        sections: list[dict[str, Any]],
        output_path: str | Path = "output.pptx",
        template: str = "default",
    ) -> PPTResult:
        """Generate PPT from structured outline using python-pptx."""
        if self._pptx is None:
            return PPTResult(error="python-pptx not installed. Install with: pip install python-pptx")

        try:
            from pptx.util import Inches, Pt
            from pptx.dml.color import RGBColor

            prs = self._pptx.Presentation()
            prs.slide_width = Inches(10)
            prs.slide_height = Inches(5.625)

            # Title slide
            slide = prs.slides.add_slide(prs.slide_layouts[0])
            slide.shapes.title.text = title
            if slide.placeholders[1]:
                slide.placeholders[1].text = "Generated by HydroWriter"

            slide_count = 1

            # Content slides
            for section in sections:
                slide = prs.slides.add_slide(prs.slide_layouts[1])
                slide.shapes.title.text = section.get("title", "")
                body = slide.placeholders[1]
                tf = body.text_frame

                for i, bullet in enumerate(section.get("bullets", [])):
                    p = tf.add_paragraph() if i > 0 else tf.paragraphs[0]
                    p.text = str(bullet)
                    p.font.size = Pt(14)

                slide_count += 1

            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            prs.save(str(output_path))

            return PPTResult(
                output_path=str(output_path),
                slide_count=slide_count,
                success=True,
                metadata={"backend": "python-pptx", "template": template},
            )
        except Exception as exc:
            return PPTResult(error=str(exc))

    async def generate_from_markdown(
        self,
        markdown_content: str,
        output_path: str | Path = "output.pptx",
    ) -> PPTResult:
        """Convert Markdown content to PPT slides.

        Splits on ## headings, each heading becomes a slide.
        """
        sections = self._parse_markdown_to_sections(markdown_content)
        title = sections[0]["title"] if sections else "Untitled"
        content_sections = sections[1:] if len(sections) > 1 else sections

        return await self.generate_from_outline(
            title=title,
            sections=content_sections,
            output_path=output_path,
        )

    async def generate_with_llm(
        self,
        topic: str,
        slide_count: int = 10,
        output_path: str | Path = "output.pptx",
    ) -> PPTResult:
        """Use LLM to generate slide outline, then render to PPT."""
        if not self.engines:
            return PPTResult(error="No engines configured for LLM-based PPT generation")

        engine = next(iter(self.engines.values()))
        prompt = (
            f"Generate a {slide_count}-slide PPT outline about: {topic}\n\n"
            "Format each slide as:\n"
            "## Slide Title\n"
            "- Bullet point 1\n"
            "- Bullet point 2\n"
            "- Bullet point 3\n\n"
            "Use clear, concise language. Include data and examples."
        )
        response = await engine.generate(prompt, system="You are a presentation designer.")
        if not response.success:
            return PPTResult(error=f"LLM generation failed: {response.metadata.get('error', 'unknown')}")

        return await self.generate_from_markdown(response.text, output_path)

    def _parse_markdown_to_sections(self, content: str) -> list[dict[str, Any]]:
        """Parse Markdown with ## headings into slide sections."""
        import re

        sections: list[dict[str, Any]] = []
        current_title = ""
        current_bullets: list[str] = []

        for line in content.split("\n"):
            heading_match = re.match(r"^#{1,3}\s+(.+)$", line)
            if heading_match:
                if current_title or current_bullets:
                    sections.append({"title": current_title, "bullets": current_bullets})
                current_title = heading_match.group(1).strip()
                current_bullets = []
            elif line.strip().startswith(("-", "*", "•")):
                bullet = re.sub(r"^[-*•]\s*", "", line.strip())
                if bullet:
                    current_bullets.append(bullet)
            elif line.strip():
                current_bullets.append(line.strip())

        if current_title or current_bullets:
            sections.append({"title": current_title, "bullets": current_bullets})

        return sections if sections else [{"title": "Untitled", "bullets": ["No content"]}]
